---
- name: install transmission-daemon and jq
  ansible.builtin.apt:
    name:
    - transmission-daemon
    - jq
    state: present

- name: stop transmission-daemon for configuration
  ansible.builtin.systemd:
    name: transmission-daemon
    state: stopped

- name: Configure transmission settings.json
  ansible.builtin.lineinfile:
    path: /etc/transmission-daemon/settings.json
    regexp: '  "{{ item.key }}":.*(,+)'
    line: '  "{{ item.key }}": {{ item.value }}\1'
    backrefs: yes
  loop: "{{ transmission_settings | dict2items }}"

- name: stop transmission-daemon for configuration
  ansible.builtin.systemd:
    name: transmission-daemon
    state: started
