---
- name: Prepare raspberry pi
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
  vars:
    install: no
    mount_state: unmounted
    samba_state: stopped
  roles:
  - samba-service
  - disk-mount
