---
- name: install samba
  ansible.builtin.apt:
    name:
    - samba
    - samba-common-bin
    state: present
  when: install

- name: Update share
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [{{ share_name }}]
      path = /srv/{{ share_name }}
      writeable=Yes
      create mask=0777
      directory mask=0777
      public=no
  notify: restart_smbd

# Setting a samba password through stdin still needs it twice
# https://stackoverflow.com/questions/3323966/echo-smbpasswd-by-stdin-doesnt-work
- name: set samba password
  ansible.builtin.shell:
    cmd: 'printf "{{ share_password }}\n{{ share_password }}" | smbpasswd -a {{ share_user }} -s'
