---
- name: Prepare raspberry pi
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
  vars:
    install: no
    mount_state: mounted
    samba_state: started
  roles:
  - disk-mount
  - samba-service
