---
- name: install hfsprogs
  ansible.builtin.apt:
    name: hfsprogs
    state: present

- name: make the mount point
  ansible.builtin.file:
    path: /srv/easystore
    state: directory

- name: mount device by label
  ansible.posix.mount:
    path: /srv/easystore
    src: LABEL=easystore
    opts: ro
    state: "{{ mount_state }}"
    fstype: hfsplus
